[package]
name = "discordia"
version = "0.1.0"
authors = ["Filippo Ziche <filippo.ziche@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "0.17.0"
dotenv = "0.15.0"
