version: '3.0'

services:
    
    database:
        container_name: database
        image: redis
        command: redis-server --appendonly yes
        ports:
            - "6379:6379"

    lavalink:
        container_name: lavalink
        build: ./lavalink
        ports:
            - "2333:2333"
